[package]
name = "cargo-big-clean"
version = "0.1.0"
authors = ["Weikeng Chen <weikeng.chen@l2iterative.com>"]
edition = "2021"
description = "a tool to clean the target directories of many Rust projects"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0.79"
walkdir = "2.4.0"
